# Generated by Django 3.0.7 on 2020-08-22 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddressBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('street', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('postal_code', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DockerImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=200)),
                ('os_type', models.CharField(max_length=200)),
                ('description', models.TextField(default='Description', max_length=500)),
                ('deploy_script', models.FileField(upload_to='bash_scripts/')),
                ('remove_script', models.FileField(upload_to='bash_scripts/')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_Name', models.CharField(max_length=200)),
                ('Device_Serial', models.CharField(max_length=200)),
                ('to_name', models.CharField(max_length=200)),
                ('to_company_name', models.CharField(max_length=200)),
                ('to_email', models.CharField(max_length=200)),
                ('to_street', models.CharField(max_length=200)),
                ('to_city', models.CharField(max_length=200)),
                ('to_state', models.CharField(max_length=200)),
                ('to_postal_code', models.CharField(max_length=200)),
                ('to_phone_number', models.CharField(max_length=200)),
                ('from_name', models.CharField(max_length=200)),
                ('from_company_name', models.CharField(max_length=200)),
                ('from_email', models.CharField(max_length=200)),
                ('from_street', models.CharField(max_length=200)),
                ('from_city', models.CharField(max_length=200)),
                ('from_state', models.CharField(max_length=200)),
                ('from_postal_code', models.CharField(max_length=200)),
                ('from_phone_number', models.CharField(max_length=200)),
                ('tracking_number_out', models.CharField(default='N/A', max_length=200)),
                ('tracking_number_in', models.CharField(default='N/A', max_length=200)),
                ('label_image_out', models.ImageField(blank=True, null=True, upload_to='outbound_labels/')),
                ('label_image_in', models.ImageField(blank=True, null=True, upload_to='inbound_labels/')),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(choices=[('RPA', 'RPA'), ('Qualys', 'Qualys'), ('VRPA', 'VRPA'), ('Laptop', 'Laptop')], max_length=200)),
                ('device_name', models.CharField(blank=True, max_length=200, null=True)),
                ('serial_number', models.CharField(max_length=200)),
                ('online', models.BooleanField(default=False)),
                ('idle', models.BooleanField(default=True)),
                ('image_hostname', models.CharField(default='0.0.0.0', max_length=200)),
                ('call_home_port', models.IntegerField(blank=True, default=0, null=True)),
                ('management_port', models.IntegerField(blank=True, default=0, null=True)),
                ('assigned_to_user', models.CharField(default='Idle', max_length=200)),
                ('assigned_to_client', models.CharField(default='Idle', max_length=200)),
                ('deployed', models.BooleanField(default=False)),
                ('weight', models.IntegerField(default=10)),
                ('length', models.IntegerField(default=13)),
                ('width', models.IntegerField(default=10)),
                ('height', models.IntegerField(default=5)),
                ('value', models.IntegerField(default=1000)),
                ('inventory_description', models.TextField(default='Inventory & Description', max_length=500)),
                ('associated_order_id', models.IntegerField(blank=True, null=True)),
                ('tracking_number_out', models.CharField(default='N/A', max_length=200)),
                ('tracking_number_in', models.CharField(default='N/A', max_length=200)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('docker_images', models.ManyToManyField(blank=True, to='Form.DockerImage')),
            ],
            options={
                'ordering': ['-online', '-deployed'],
            },
        ),
    ]
